matrix:
  include:
    - language: cpp
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq 
      install:
        - sudo apt-get install -qq g++-6 --allow-unauthenticated
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
        - ./fetch_db
      compiler: 
        - gcc
        # - clang
      env: 
        - OMP_NUM_THREADS=4
      script:
        - make
        - ./bin/elfin -x xdb.json -i input/test_input_1696.json

branches:
  only:
  - master

notifications:
  email:
  - joyyeh.tw@gmail.com
