language: cpp
dist: trusty
git:
    submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq 
install:
  - sudo apt-get install -qq g++-8 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - ./fetch_db
compiler: 
  - gcc
  # - clang
env: 
  - OMP_NUM_THREADS=4
script:
  - make -j4 unit
  - make test

notifications:
  email:
  - joyyeh.tw@gmail.com
