language: cpp
dist: trusty
git:
    submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq 
  - sudo apt-get install -qq g++-8 --allow-unauthenticated
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - make clean
install:
  - g++ --version
  - ./fetch_db
  - make -j${OMP_NUM_THREADS}
compiler: 
  - gcc
  # - clang
env: 
  - OMP_NUM_THREADS=`grep -c ^processor /proc/cpuinfo`
script:
  - make unit
  
notifications:
  email:
  - joyyeh.tw@gmail.com
